openapi: 3.0.0
info:
  title: Anwendungsfall Alternative Zuweisung
  version: 1.0.0
  description: |-
    # Header 1
    Text under Header 1 and more

    ## Subheader 1
    And so on

    ## Test für Link zu einem API Endpunkt

    Hier geht es dann zu [einem POST Request](https://gematiktest.stoplight.io/docs/test-openapi/6722ae04697da-create-a-task-create)
tags:
  - name: Alt-Test
  - name: Zuw-Test
paths:
  /Task/$create:
    post:
      tags:
        - Rezept abrufen
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/CreateTask'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTask'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/fhir+xml
        - name: Authorization
          in: header
          schema:
            type: string
          example: 'Bearer {{access_token_arztpraxis}}'
      responses:
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example: id-123456
            application/xml:
              schema:
                type: object
                properties: {}
      summary: Erstellen eines Tasks
components:
  schemas:
    CreateTask:
      type: object
      xml:
        name: Parameters
        namespace: 'http://hl7.org/fhir'
      properties:
        parameter:
          properties:
            name:
              properties:
                value:
                  example: workflowType
                  xml:
                    attribute: true
                    wrapped: true
            valueCoding:
              properties:
                system:
                  properties:
                    value:
                      example: 'https://gematik.de/fhir/CodeSystem/Flowtype'
                      xml:
                        attribute: true
                        wrapped: true
                code:
                  properties:
                    value:
                      example: '160'
                      xml:
                        attribute: true
                        wrapped: true
  securitySchemes: {}
servers: []
