openapi: 3.0.0
info:
  title: E-Rezept Fachdienst API
  version: 1.0.0
  description: OpenAPI Beschreibung der Endpunkte vom E-Rezept Fachdienst
servers:
  - description: RU-DEV
    url: 'https://erp-dev.zentral.erp.splitdns.ti-dienste.de'
  - description: RU
    url: 'https://erp-ref.zentral.erp.splitdns.ti-dienste.de'
  - description: PU
    url: 'https://erp.zentral.erp.splitdns.ti-dienste.de'
tags:
  - name: Arztpraxis
  - name: Quittung abrufen
  - name: Quittung erneut abrufen
  - name: Rezept abrufen
  - name: Rezept löschen
  - name: Rezept zurückgeben
paths:
  /Task/$create:
    post:
      tags:
        - Arztpraxis
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/fhir+xml
        - name: Authorization
          in: header
          schema:
            type: string
          example: 'Bearer {{access_token_arztpraxis}}'
      responses:
        '201':
          description: '[Task mit AccessCode](https://simplifier.net/erezept-workflow/gem_erp_pr_task)'
          content:
            application/fhir+xml:
              examples:
                'Task (WF: 160)':
                  value: |-
                    <Task xmlns="http://hl7.org/fhir">
                        <id value="160.123.456.789.123.58"/>
                        <meta>
                            <versionId value="1"/>
                            <lastUpdated value="2020-03-02T08:26:21.594+00:00"/>
                            <profile value="https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_PR_Task|1.2"/>
                            <source value="#AsYR9plLkvONJAiv"/>
                        </meta>
                        <extension url="https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_EX_PrescriptionType">
                            <valueCodeableConcept>
                                <coding>
                                    <system value="https://gematik.de/fhir/erp/CodeSystem/GEM_ERP_CS_FlowType" />
                                    <code value="160" />
                                    <display value="Muster 16 (Apothekenpflichtige Arzneimittel)" />
                                </coding>
                            </valueCodeableConcept>
                        </extension>
                        <extension url="https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_EX_ExpiryDate">
                            <valueDateTime value="2020-06-02" />
                        </extension>
                        <extension url="https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_EX_AcceptDate">
                            <valueDateTime value="2020-04-01" />
                        </extension>
                        <identifier>
                            <use value="official"/>
                            <system value="https://gematik.de/fhir/erp/NamingSystem/GEM_ERP_NS_PrescriptionId"/>
                            <value value="160.123.456.789.123.58"/>
                        </identifier>
                        <identifier>
                            <use value="official"/>
                            <system value="https://gematik.de/fhir/erp/NamingSystem/GEM_ERP_NS_AccessCode"/>
                            <value value="777bea0e13cc9c42ceec14aec3ddee2263325dc2c6c699db115f58fe423607ea"/>
                        </identifier>
                        <status value="draft"/>
                        <intent value="order"/>
                        <authoredOn value="2020-03-02T08:25:05+00:00"/>
                        <lastModified value="2020-03-02T08:25:05+00:00"/>
                        <performerType>
                            <coding>
                                <system value="urn:ietf:rfc:3986"/>
                                <code value="urn:oid:1.2.276.0.76.4.54"/>
                                <display value="Öffentliche Apotheke"/>
                            </coding>
                            <text value="Apotheke"/>
                        </performerType>
                    </Task>
                'Task (WF: 200)':
                  value: |-
                    <Task xmlns="http://hl7.org/fhir">
                        <id value="200.123.456.789.123.58"/>
                        <meta>
                            <versionId value="1"/>
                            <lastUpdated value="2020-03-02T08:26:21.594+00:00"/>
                            <profile value="https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_PR_Task|1.2"/>
                            <source value="#AsYR9plLkvONJAiv"/>
                        </meta>
                        <extension url="https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_EX_PrescriptionType">
                            <valueCodeableConcept>
                                <coding>
                                    <system value="https://gematik.de/fhir/erp/CodeSystem/GEM_ERP_CS_FlowType" />
                                    <code value="200" />
                                    <display value="Muster 16 (Apothekenpflichtige Arzneimittel)" />
                                </coding>
                            </valueCodeableConcept>
                        </extension>
                        <extension url="https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_EX_ExpiryDate">
                            <valueDateTime value="2020-06-02" />
                        </extension>
                        <extension url="https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_EX_AcceptDate">
                            <valueDateTime value="2020-04-01" />
                        </extension>
                        <identifier>
                            <use value="official"/>
                            <system value="https://gematik.de/fhir/erp/NamingSystem/GEM_ERP_NS_PrescriptionId"/>
                            <value value="200.123.456.789.123.58"/>
                        </identifier>
                        <identifier>
                            <use value="official"/>
                            <system value="https://gematik.de/fhir/erp/NamingSystem/GEM_ERP_NS_AccessCode"/>
                            <value value="777bea0e13cc9c42ceec14aec3ddee2263325dc2c6c699db115f58fe423607ea"/>
                        </identifier>
                        <status value="draft"/>
                        <intent value="order"/>
                        <authoredOn value="2020-03-02T08:25:05+00:00"/>
                        <lastModified value="2020-03-02T08:25:05+00:00"/>
                        <performerType>
                            <coding>
                                <system value="urn:ietf:rfc:3986"/>
                                <code value="urn:oid:1.2.276.0.76.4.54"/>
                                <display value="Öffentliche Apotheke"/>
                            </coding>
                            <text value="Apotheke"/>
                        </performerType>
                    </Task>
      description: ''
      requestBody:
        content:
          application/fhir+xml:
            schema:
              type: object
              properties: {}
            examples:
              Workflow 160:
                value: |-
                  <Parameters xmlns="http://hl7.org/fhir">
                    <parameter>
                      <name value="workflowType"/>
                      <valueCoding>
                        <system value="https://gematik.de/fhir/erp/CodeSystem/GEM_ERP_CS_FlowType"/>
                        <code value="160"/>
                      </valueCoding>
                    </parameter>
                  </Parameters>
              Workflow 169:
                value: |-
                  <Parameters xmlns="http://hl7.org/fhir">
                    <parameter>
                      <name value="workflowType"/>
                      <valueCoding>
                        <system value="https://gematik.de/fhir/erp/CodeSystem/GEM_ERP_CS_FlowType"/>
                        <code value="169"/>
                      </valueCoding>
                    </parameter>
                  </Parameters>
  '/Task/{task_id}/$activate':
    post:
      tags:
        - Rezept abrufen
        - Arztpraxis
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/ActivateTask'
          application/json:
            schema:
              $ref: '#/components/schemas/ActivateTask'
      parameters:
        - name: X-AccessCode
          in: header
          schema:
            type: string
          example: '{{task_access_code}}'
        - name: Authorization
          in: header
          schema:
            type: string
          example: 'Bearer {{access_token_arztpraxis}}'
        - name: task_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: '[Successful response](https://simplifier.net/erezept-workflow/gem_erp_pr_task)'
      summary: Activate Prescription
      description: '[Get IDP Token](../docs/idp_token.md)'
  '/Task/{task_id}/$accept':
    post:
      tags:
        - Rezept abrufen
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: 'application/fhir+xml;q=1.0, application/json+fhir;q=0.9'
        - name: Authorization
          in: header
          schema:
            type: string
          example: 'Bearer {{access_token_apotheke}}'
        - name: x-accesscode
          in: header
          schema:
            type: string
          example: 418af289f80ca1f7189cff6dc43cbf302224f543f13a7c0b479f8042777c67ec
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/fhir+xml
        - name: Accept-Charset
          in: header
          schema:
            type: string
          example: utf-8
        - name: ac
          in: query
          schema:
            type: string
          example: '{{task_access_code}}'
        - name: task_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
  '/Task/{task_id}/$reject':
    post:
      tags:
        - Rezept zurückgeben
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/fhir+xml
        - name: Authorization
          in: header
          schema:
            type: string
          example: 'Bearer {{access_token_apotheke}}'
        - name: secret
          in: query
          schema:
            type: string
          example: '{{task_secret}}'
        - name: task_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Successful response
      summary: Ein Rezept zurückweisen
  '/Task/{task_id}/$abort':
    post:
      tags:
        - Rezept löschen
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/fhir+xml
        - name: Authorization
          in: header
          schema:
            type: string
          example: 'Bearer {{access_token_arztpraxis}}'
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/fhir+xml; charset=UTF-8
        - name: X-AccessCode
          in: header
          schema:
            type: string
          example: '{{task_access_code}}'
        - name: task_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Successful response
  '/Task/{task_id}/$close':
    post:
      tags:
        - Quittung abrufen
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/MedicationDispense'
          application/json:
            schema:
              $ref: '#/components/schemas/MedicationDispense'
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/fhir+xml
        - name: Authorization
          in: header
          schema:
            type: string
          example: 'Bearer {{access_token_apotheke}}'
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/fhir+xml; charset=UTF-8
        - name: secret
          in: query
          schema:
            type: string
          example: '{{task_secret}}'
        - name: task_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: '[Successful response](https://simplifier.net/erezept-workflow/gem_erp_pr_task)'
  '/Task/{task_id}':
    get:
      tags:
        - Quittung erneut abrufen
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: 'Bearer {{access_token_patient}}'
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/fhir+json; charset=UTF-8
        - name: X-Api-Key
          in: header
          schema:
            type: string
          example: DEpsSHb/5DKJwV3TjhZQXw==
        - name: Accept
          in: header
          schema:
            type: string
          example: application/fhir+json
        - name: task_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
components:
  schemas: {}
  examples: {}
  responses: {}
  requestBodies: {}
